@call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
@call "C:\Users\scott\esp\esp-idf\export.bat"
set PATH="C:\Users\scott\.espressif\python_env\idf4.4_py3.8_env\Scripts;%PATH%"
set PATH="C:\Users\scott/.espressif/tools/xtensa-esp32-elf-clang/esp-14.0.0-20220415-x86_64-pc-windows-msvc/bin/;%PATH%"
set LIBCLANG_PATH="C:\Users\scott\.espressif\tools\xtensa-esp32-elf-clang\esp-14.0.0-20220415-x86_64-pc-windows-msvc\bin"
set PIP_USER="no"
